### ISSUE TITLE
Client crash - FORGE issue?

### ISSUE THREAD

**Issue by marduvGitHub** [CovertJaguar/Railcraft#584]
Hi
After I did update the FORGE version running on server and client the client crashes when right clicking the steam boiler.
I suspect there is a issue with FORGE and registration of fluid, se paste bin: http://pastebin.com/Rf91q39R

I have tested several versions of the FORGE this include 10.13.3.1365 and latest version 10.13.3.1373
Yes I'm running 9.5.0.0 of Railcraft

**Comment by hamiltenor** [comment]
Encountering a similar problem, appears to be with the way Forge now handles fluids.

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:29)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59)
	at mods.railcraft.common.fluids.TankManager.processGuiUpdate(TankManager.java:192)
	at mods.railcraft.common.gui.containers.ContainerCokeOven.func_75137_b(ContainerCokeOven.java:98)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

**Comment by Tsunayoshi** [comment]
>1355 there is a change in the fluidstack.
It is already fixed in the dev version and will be relased with railcraft 9.6
dulicate https://github.com/CovertJaguar/Railcraft/issues/581

**Comment by marduvGitHub** [comment]
@Tsunayoshi Thanks, I was a bit too quick when I did a search :-(
