### ISSUE TITLE
Steam Turbine Housing crashing without IC2.

### ISSUE THREAD

**Issue by ruifung** [CovertJaguar/Railcraft#658]
This crash happens if the steam turbine housing is placed without IC2. The steam turbine housing however, is craftable.

exception stack trace:
```
Description: Unexpected error

java.lang.NoClassDefFoundError: mods/railcraft/common/plugins/ic2/TileIC2MultiEmitterDelegate
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at mods.railcraft.common.blocks.machine.alpha.EnumMachineAlpha.getTileEntity(EnumMachineAlpha.java:137)
	at mods.railcraft.common.blocks.machine.alpha.EnumMachineAlpha.getTileEntity(EnumMachineAlpha.java:36)
	at mods.railcraft.common.blocks.machine.BlockMachine.createTileEntity(BlockMachine.java:293)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.World.func_147438_o(World.java:2540)
	at fastcraft.b.u.func_147438_o(F:58)
	at mods.railcraft.common.blocks.machine.BlockMachine.getLightValue(BlockMachine.java:305)
	at fastcraft.b.u.a(F:328)
	at fastcraft.b.u.a(F:131)
	at fastcraft.a.f.a(F:88)
	at fastcraft.a.f.a(F:180)
	at fastcraft.Hooks.c(F:55)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:637)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at mods.railcraft.common.blocks.machine.ItemMachine.placeBlockAt(ItemMachine.java:41)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.ClassNotFoundException: mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 41 more
Caused by: java.lang.NoClassDefFoundError: ic2/api/energy/tile/IEnergySource
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 43 more
Caused by: java.lang.ClassNotFoundException: ic2.api.energy.tile.IEnergySource
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 47 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at mods.railcraft.common.blocks.machine.alpha.EnumMachineAlpha.getTileEntity(EnumMachineAlpha.java:137)
	at mods.railcraft.common.blocks.machine.alpha.EnumMachineAlpha.getTileEntity(EnumMachineAlpha.java:36)
	at mods.railcraft.common.blocks.machine.BlockMachine.createTileEntity(BlockMachine.java:293)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.World.func_147438_o(World.java:2540)
	at fastcraft.b.u.func_147438_o(F:58)
	at mods.railcraft.common.blocks.machine.BlockMachine.getLightValue(BlockMachine.java:305)
	at fastcraft.b.u.a(F:328)
	at fastcraft.b.u.a(F:131)
	at fastcraft.a.f.a(F:88)
	at fastcraft.a.f.a(F:180)
	at fastcraft.Hooks.c(F:55)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:637)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at mods.railcraft.common.blocks.machine.ItemMachine.placeBlockAt(ItemMachine.java:41)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
```

**Comment by Forecaster** [comment]
What version of Railcraft are you using?

**Comment by ruifung** [comment]
9.6.1.0 This is the latest version on the site right?

**Comment by Forecaster** [comment]
Please post the entire stacktrace on pastebin or some similar service and link it here.

**Comment by ruifung** [comment]
Crash log: http://paste.ee/p/FjPMd
Don't really have the forge logs around anymore.

I wonder if this can be recreated using railcraft alone..?

**Comment by Forecaster** [comment]
The turbine does not require ic2 anymore. It can be used to power the electric blocks in Railcraft even when ic2 is not present.

One of the other mods you are using may include the ic2 api which might be confusing Railcraft.

**Comment by ruifung** [comment]
Right. It's definitely that then. I am unable to recreate with railcraft only.

Also load log, in case it might shed some light on which mod in particular is causing this:
http://paste.ee/p/vj4ZG

**Comment by ruifung** [comment]
I've managed to narrow it down to the minimum number of mods required to reproduce it.

- NotEnoughItems 1.0.5.111
- Mekanism 8.1.5.246
- Railcraft 9.6.1.0
- CoFHCore 3.0.3-303

The dependencies for the above which are installed are:
- CodeChickenCore 1.0.7.46
- CodeChickenLib 1.1.3.138
- ForgeMultipart 1.1.2.331

Minecraft does not start at all with Mekanism and Railcraft installed, but no CoFHCore. (See #660)
The crash does not occur if NEI is not present.

**Comment by happysmash27** [comment]
Why is this low priority? Mekanism is a pretty important mod and Railcraft is too! I really don't want to have to go without them.

**Comment by CovertJaguar** [comment]
Well it's an interesting question. Issue management is basically a triage situation. I have limited resources to spend on fixing issues, so some issues are simply going to receive more attention than others. Most cross-mod interactions get labeled low priority for the simple reason that they only affect a small subset of users. Additionally they are generally hard to identify and fix, and it may not even be Railcraft that needs fixing. And to round things off, this report remains unverified. Which means I can't even be sure it's not something unique to the reportee's setup or simple user error of some kind (no offense to the reportee, it happens). No one else has reported the same issue and no one has duplicated it either. Reports with only one reportee are almost always low priority. My time is finite, repeatable issues that affect multiple people are going to get my attention first. The best way to move an issue up the list is to demonstrate that it is a widespread repeatable issue by providing me with an independent reproduction. The more information I have, the less resources are required to find a fix.
