### ISSUE TITLE
Wierd crash from steam boilers using thermal dynamics

### ISSUE THREAD

**Issue by magnus97** [CovertJaguar/Railcraft#659]
I dont know if it is related to this mod or thermal dynamics anyway this is the crash log

Description: Ticking memory connection

java.lang.ClassCastException: mods.railcraft.common.blocks.machine.beta.TileBoilerTankHigh cannot be cast to cofh.thermaldynamics.block.TileTDBase
	at cofh.thermaldynamics.block.BlockTDBase.isSideSolid(BlockTDBase.java:53)
	at com.stuntmania.placeableitems.handler.RightClickHandler.rightClick(RightClickHandler.java:163)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_949_RightClickHandler_rightClick_PlayerInteractEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:353)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by CovertJaguar** [comment]
Appears to be a ThermalDynamics issue.

**Comment by XFactHD** [comment]
@magnus97 I think you should report this to the dev of placeable items.
