### ISSUE TITLE
Crashing with current set Railcraft

### ISSUE THREAD

**Issue by Remanscimitar** [CovertJaguar/Railcraft#684]
Just installed the latest version of Railcraft (9.6.1.0) and seem to get a crash report

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 9/2/15 7:46 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.kingrunes.somnia.server.ForgeEventHandler.onEntityConstructing(ForgeEventHandler.java:23)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_381_ForgeEventHandler_onEntityConstructing_EntityConstructing.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.entity.Entity.<init>(Entity.java:179)
	at net.minecraft.entity.item.EntityMinecart.<init>(EntityMinecart.java:66)
	at net.minecraft.entity.item.EntityMinecart.<init>(EntityMinecart.java:133)
	at net.minecraft.entity.item.EntityMinecartEmpty.<init>(EntityMinecartEmpty.java:17)
	at mods.railcraft.common.carts.EntityCartBasic.<init>(EntityCartBasic.java:21)
	at mods.railcraft.common.carts.EnumCart.makeCart(EnumCart.java:115)
	at mods.railcraft.client.core.ClientProxy.initClient(ClientProxy.java:118)
	at mods.railcraft.common.core.Railcraft.postInit(Railcraft.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.kingrunes.somnia.server.ForgeEventHandler.onEntityConstructing(ForgeEventHandler.java:23)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_381_ForgeEventHandler_onEntityConstructing_EntityConstructing.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.entity.Entity.<init>(Entity.java:179)
	at net.minecraft.entity.item.EntityMinecart.<init>(EntityMinecart.java:66)
	at net.minecraft.entity.item.EntityMinecart.<init>(EntityMinecart.java:133)
	at net.minecraft.entity.item.EntityMinecartEmpty.<init>(EntityMinecartEmpty.java:17)
	at mods.railcraft.common.carts.EntityCartBasic.<init>(EntityCartBasic.java:21)
	at mods.railcraft.common.carts.EnumCart.makeCart(EnumCart.java:115)
	at mods.railcraft.client.core.ClientProxy.initClient(ClientProxy.java:118)
	at mods.railcraft.common.core.Railcraft.postInit(Railcraft.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 332792240 bytes (317 MB) / 938483712 bytes (895 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJ	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJ	SomniaCore{1.3.1.23} [SomniaCore] (minecraft.jar) 
	UCHIJ	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJ	AIRI{3.0.0-1.7.10} [AIRI] ([1.7.10-10.13.0.1158][3.0.2-1.7.10] AIRI.jar) 
	UCHIJ	AliensVsPredator{3.9.14-1.7.10} [AliensVsPredator] ([1.7.10-10.13.0.1158][3.9.14-1.7.10] AliensVsPredator.jar) 
	UCHIJ	Backpack{2.0.0} [Backpack] (backpack-2.0.0-1.7.x.jar) 
	UCHIJ	bdlib{1.9.1.97} [BD Lib] (bdlib-1.9.1.97-mc1.7.10.jar) 
	UCHIJ	BuildCraft|Core{7.0.21} [BuildCraft] (buildcraft-7.0.21.jar) 
	UCHIJ	BuildCraft|Silicon{7.0.21} [BC Silicon] (buildcraft-7.0.21.jar) 
	UCHIJ	BuildCraft|Factory{7.0.21} [BC Factory] (buildcraft-7.0.21.jar) 
	UCHIJ	BuildCraft|Builders{7.0.21} [BC Builders] (buildcraft-7.0.21.jar) 
	UCHIJ	BuildCraft|Energy{7.0.21} [BC Energy] (buildcraft-7.0.21.jar) 
	UCHIJ	BuildCraft|Robotics{7.0.21} [BC Robotics] (buildcraft-7.0.21.jar) 
	UCHIJ	BuildCraft|Transport{7.0.21} [BC Transport] (buildcraft-7.0.21.jar) 
	UCHIJ	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UCHIJ	bcadditions{2.2.0} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.2.0.jar) 
	UCHIJ	IC2{2.2.727-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.727-experimental.jar) 
	UCHIJ	Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar) 
	UCHIJ	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJ	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCHIJ	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V7f.jar) 
	UCHIJ	CaveControl{1.0} [CaveControl] (CaveControl 1.7.10 V7a.jar) 
	UCHIJ	ChromatiCraft{1.0} [ChromatiCraft] (ChromatiCraft 1.7.10 V7e.jar) 
	UCHIJ	ComputerCraft{1.74} [ComputerCraft] (ComputerCraft1.74.jar) 
	UCHIJ	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1.zip) 
	UCHIJ	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJ	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V7f.jar) 
	UCHIJ	ElectriCraft{1.0} [ElectriCraft] (ElectriCraft 1.7.10 V7e.jar) 
	UCHIJ	ExpandedRedstone{1.0} [Expanded Redstone] (ExpandedRedstone 1.7.10 V7a.jar) 
	UCHIJ	advgenerators{0.9.17.102} [Advanced Generators] (generators-0.9.17.102-mc1.7.10.jar) 
	UCHIJ	GeoStrata{1.0} [GeoStrata] (GeoStrata 1.7.10 V7e.jar) 
	UCHIJ	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) 
	UCHIJ	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) 
	UCHIJ	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) 
	UCHIJ	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) 
	UCHIJ	Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) 
	UCHIJ	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) 
	UCHIJ	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) 
	UCHIJ	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) 
	UCHIJ	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) 
	UCHIJ	hyperioncraft{1.7.10-0.2.3a} [HyperionCraft] (hyperioncraft-1.7.10-0.2.3a.jar) 
	UCHIJ	RadixCore{2.0.1} [RadixCore] (RadixCore-2.0.1-1.7.10-universal.jar) 
	UCHIJ	MCA{5.0.5_1} [Minecraft Comes Alive] (MCA-5.0.5_1-1.7.10-universal.jar) 
	UCHIJ	MeteorCraft{1.0} [MeteorCraft] (MeteorCraft 1.7.10 V7a.jar) 
	UCHIJ	Oceancraft{1.4.1} [Oceancraft] (Oceancraft-1.4.1.jar) 
	UCHIE	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UCHIJ	ReactorCraft{1.0} [ReactorCraft] (ReactorCraft 1.7.10 V7f.jar) 
	UCHIJ	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHIJ	RWG{Alpha 1.3.2} [Realistic World Gen Alpha] (RWG-alpha-1.3.2.jar) 
	UCHIJ	Somnia{-au} [Somnia] (Somnia-1.4.1.23.jar) 
	UCHIJ	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UCHIJ	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3621' Renderer: 'Intel(R) HD Graphics 4400'
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	List of loaded APIs: 
		* bcadditionsAPI (2.1.1) from BuildcraftAdditions-1.7.10-2.2.0.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|blueprints (1.3) from buildcraft-7.0.21.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|core (1.4) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.0.21.jar
		* BuildCraftAPI|events (1.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.0.21.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.0.21.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.0.21.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.0.21.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|robotics (2.1) from buildcraft-7.0.21.jar
		* BuildCraftAPI|statements (1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|tiles (1.1) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|tools (1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.0.21.jar
		* CoFHAPI (1.7.10R1.0.1) from buildcraft-7.0.21.jar
		* CoFHAPI|energy (1.7.10R1.0.1) from BuildcraftAdditions-1.7.10-2.2.0.jar
		* ComputerCraft|API (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|FileSystem (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|Lua (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|Media (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|Peripheral (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|Permissions (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|Redstone (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|Turtle (1.74) from ComputerCraft1.74.jar
		* ForestryAPI|apiculture (3.5.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|arboriculture (2.3.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|circuits (2.0.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|core (3.2.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|genetics (3.3.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|lepidopterology (1.1) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|recipes (3.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|world (1.1.0) from forestry_1.7.10-3.6.3.20.jar
		* GrowthcraftAPI|Bees (2.0) from growthcraft-bees-1.7.10-2.1.0.jar
		* GrowthcraftAPI|Cellar (2.0) from growthcraft-cellar-1.7.10-2.1.0a.jar
		* GrowthcraftAPI|Core (2.0) from growthcraft-core-1.7.10-2.1.0a.jar
		* GrowthcraftAPI|FishTrap (2.0) from growthcraft-fishtrap-1.7.10-2.1.0a.jar
		* IC2API (1.0) from industrialcraft-2-2.2.727-experimental.jar
		* minechemAPI (1.7.10R1) from DragonAPI 1.7.10 V7f.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|carts (1.3.1) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|core (1.3.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|signals (1.3.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.6.1.0.jar
	Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.2.0 - Build 10.18.10.3621, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Vault-Tec Resource Pack Alpha (v1.1.7).zip, TheZone64.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

I managed a few weeks back to get it to work before trying to update to 1.8 series Minecraft and found out most mods I play were not updated yet to 1.8 and reverted back to 1.7.10, went through some old tickets to see what info would be beneficial. Have not yet touched the config files yet.

**Comment by AEnterprise** [comment]
```
at com.kingrunes.somnia.server.ForgeEventHandler.onEntityConstructing(ForgeEventHandler.java:23)
```
it's not railcraft that is crashing here

**Comment by Remanscimitar** [comment]
Somnia 1.4.1.23 was the cause, thanks for helping out

**Comment by liach** [comment]
Actually it is hard to prevent it since minecraft mechanic need you to create an instance of  entity/tileentity to get their information.
