### ISSUE TITLE
disabling plates gives an error

### ISSUE THREAD

**Issue by SirKastros** [CovertJaguar/Railcraft#724]
when I disable railcraft plates I get this crash report

--- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 10/28/15 12:16 PM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 3
	at mods.railcraft.common.items.RailcraftItem.getRecipeObject(RailcraftItem.java:126)
	at mods.railcraft.common.modules.ModuleElectricity.initFirst(ModuleElectricity.java:82)
	at mods.railcraft.common.modules.ModuleManager.initFirst(ModuleManager.java:254)
	at mods.railcraft.common.modules.ModuleManager.preInit(ModuleManager.java:174)
	at mods.railcraft.common.core.Railcraft.preInit(Railcraft.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mods.railcraft.common.items.RailcraftItem.getRecipeObject(RailcraftItem.java:126)
	at mods.railcraft.common.modules.ModuleElectricity.initFirst(ModuleElectricity.java:82)
	at mods.railcraft.common.modules.ModuleManager.initFirst(ModuleManager.java:254)
	at mods.railcraft.common.modules.ModuleManager.preInit(ModuleManager.java:174)
	at mods.railcraft.common.core.Railcraft.preInit(Railcraft.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1004182152 bytes (957 MB) / 1745354752 bytes (1664 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCH	Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCH	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCH	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
	UCH	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCH	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCH	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) 
	UCH	bdlib{1.9.3.107} [BD Lib] (bdlib-1.9.3.107-mc1.7.10.jar) 
	UCH	BiblioCraft{1.11.3} [BiblioCraft] (BiblioCraft[v1.11.3][MC1.7.10].jar) 
	UCH	BuildCraft|Core{7.1.12} [BuildCraft] (buildcraft-7.1.12.jar) 
	UCH	BuildCraft|Builders{7.1.12} [BC Builders] (buildcraft-7.1.12.jar) 
	UCH	BuildCraft|Transport{7.1.12} [BC Transport] (buildcraft-7.1.12.jar) 
	UCH	BuildCraft|Energy{7.1.12} [BC Energy] (buildcraft-7.1.12.jar) 
	UCH	BuildCraft|Silicon{7.1.12} [BC Silicon] (buildcraft-7.1.12.jar) 
	UCH	BuildCraft|Robotics{7.1.12} [BC Robotics] (buildcraft-7.1.12.jar) 
	UCH	BuildCraft|Factory{7.1.12} [BC Factory] (buildcraft-7.1.12.jar) 
	UCH	IC2{2.2.790-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.790-experimental.jar) 
	UCH	Forestry{4.0.11.40} [Forestry for Minecraft] (forestry_1.7.10-4.0.11.40.jar) 
	UCH	BuildCraft|Compat{7.1.2} [BuildCraft Compat] (buildcraft-compat-7.1.2.jar) 
	UCH	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCH	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCH	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar) 
	UCH	gendustry{1.6.2.127} [GenDustry] (gendustry-1.6.2.127-mc1.7.10.jar) 
	UCH	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCH	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCH	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
	UCH	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	neiintegration{1.0.13} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.13.jar) 
	UCH	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) 
	UCH	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCH	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCH	pressure{1.2.4.124} [Pressure Pipes] (pressure-1.2.4.124-mc1.7.10.jar) 
	UCE	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCH	WailaHarvestability{1.1.3} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.3.jar) 
	UCH	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon R7 200 Series'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	List of loaded APIs: 
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.12.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.12.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.12.jar
		* BuildCraftAPI|core (1.0) from buildcraft-7.1.12.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.1.12.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.12.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.12.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.12.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.12.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.12.jar
		* BuildCraftAPI|items (1.0) from Railcraft_1.7.10-9.8.0.0.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.1.12.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.12.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.12.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.1.12.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.12.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.12.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.12.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.1.12.jar
		* BuildCraftAPI|tools (1.0) from extrautilities-1.2.11.jar
		* BuildCraftAPI|transport (4.0) from Railcraft_1.7.10-9.8.0.0.jar
		* CoFHAPI (1.7.10R1.0.1) from Railcraft_1.7.10-9.8.0.0.jar
		* CoFHAPI|block (1.7.10R1.0.13B1) from extrautilities-1.2.11.jar
		* CoFHAPI|energy (1.7.10R1.0.13B1) from extrautilities-1.2.11.jar
		* CoFHAPI|inventory (1.7.10R1.0.1) from buildcraft-compat-7.1.2.jar
		* CoFHAPI|item (1.7.10R1.0.13B1) from extrautilities-1.2.11.jar
		* CoFHAPI|transport (1.7.10R1.0.1) from buildcraft-compat-7.1.2.jar
		* ForestryAPI|apiculture (4.4.0) from forestry_1.7.10-4.0.11.40.jar
		* ForestryAPI|arboriculture (4.2.0) from forestry_1.7.10-4.0.11.40.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.0.11.40.jar
		* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.0.11.40.jar
		* ForestryAPI|farming (2.0.0) from forestry_1.7.10-4.0.11.40.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.0.11.40.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.0.11.40.jar
		* ForestryAPI|genetics (4.3.0) from forestry_1.7.10-4.0.11.40.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.0.11.40.jar
		* ForestryAPI|lepidopterology (1.2.0) from forestry_1.7.10-4.0.11.40.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.0.11.40.jar
		* ForestryAPI|recipes (5.1.0) from forestry_1.7.10-4.0.11.40.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.0.11.40.jar
		* ForestryAPI|world (2.0.0) from forestry_1.7.10-4.0.11.40.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.2.127-mc1.7.10.jar
		* IC2API (1.0) from industrialcraft-2-2.2.790-experimental.jar
		* OpenBlocks|API (1.0) from OpenBlocks-1.7.10-1.4.4.jar
		* pressureAPI (1.2.4.124) from pressure-1.2.4.124-mc1.7.10.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|carts (1.5.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|core (1.4.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|signals (1.3.4) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.8.0.0.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Launched Version: forge-10.13.4.1517
	LWJGL: 2.9.1
	OpenGL: AMD Radeon R7 200 Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by SirKastros** [comment]
I was trying to disable the plates from railcraft so GT plates will be made of them.

**Comment by CovertJaguar** [comment]
It would appear that I forgot to give the Copper Plate an alternative replacement. Btw, if you disable plates, everything thing Railcraft will use Ingots instead. This may not be what you are aiming for.

**Comment by Vexatos** [comment]
Mind that GregTech adds all Railcraft plates to the Ore Dictionary (the tin plate will be registered as `plateTinAlloy` due to being made of tin and iron); all GT recipes use the OreDictionary, Railcraft recipes using plates do not.
