### ISSUE TITLE
Client crash due to chunk loader on changing maps

### ISSUE THREAD

**Issue by damnedsky** [CovertJaguar/Railcraft#757]
How to reproduce:
I have a chunk loader in an area with Forestry Apiaries. I exit the world, enter my test world and come back or simply re-enter WITHOUT closing the client.

Error text:
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 12/30/15 1:12 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.google.common.collect.LinkedHashMultimap.create(LinkedHashMultimap.java:119)
	at net.minecraftforge.common.ForgeChunkManager.unforceChunk(ForgeChunkManager.java:783)
	at mods.railcraft.common.blocks.machine.alpha.TileAnchorWorld.setTicket(TileAnchorWorld.java:370)
	at mods.railcraft.common.blocks.machine.alpha.TileAnchorWorld.forceChunkLoading(TileAnchorWorld.java:385)
	at mods.railcraft.common.util.misc.ChunkManager.ticketsLoaded(ChunkManager.java:174)
	at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:523)
	at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:64)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_0_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 822578440 bytes (784 MB) / 2599944192 bytes (2479 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 15, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 89 mods loaded, 89 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
	UCHIJAAAAAAAAAAAA	Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
	UCHIJAAAAAAAAAAAA	appliedenergistics2-core{rv3-beta-2} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAAAAAAAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAAAAAAAAAA	backpacks16840{3.0.5} [Backpacks!] (zz-backpacks 1.7.10 - 3.0.5.jar) 
	UCHIJAAAAAAAAAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAAAAAAAAAA	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCHIJAAAAAAAAAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHIJAAAAAAAAAAAA	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHIJAAAAAAAAAAAA	appliedenergistics2{rv3-beta-2} [Applied Energistics 2] (appliedenergistics2-rv3-beta-2.jar) 
	UCHIJAAAAAAAAAAAA	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJAAAAAAAAAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAAAAAAAAAA	ExtrabiomesXL{3.16.3} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.3.jar) 
	UCHIJAAAAAAAAAAAA	BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition] (BiblioWoods[ExtraBiomesXL][v1.4].jar) 
	UCHIJAAAAAAAAAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAAAAAAAAAA	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAAAAAAA	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAAAAAAA	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAAAAAAA	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAAAAAAA	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAAAAAAA	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAAAAAAA	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
	UCHIJAAAAAAAAAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAAAAAAAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCHIJAAAAAAAAAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAAAAAAAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAAAAAAAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAAAAAAAAAAAA	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UCHIJAAAAAAAAAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAAAAAAAAAA	EnhancedInventories{1.7.10-1.1.8} [Enhanced Inventories] (EnhancedInventories-1.7.10-1.1.8.jar) 
	UCHIJAAAAAAAAAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJAAAAAAAAAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAAAAAAAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAAAAAAAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAAAAAAAAAA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJAAAAAAAAAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAAAAAAAAAA	fastleafdecay{1.3} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.3.jar) 
	UCHIJAAAAAAAAAAAA	HardcoreEnderExpansion{1.8.4} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.4.jar) 
	UCHIJAAAAAAAAAAAA	Forestry{4.2.3.51} [Forestry for Minecraft] (forestry_1.7.10-4.2.3.51.jar) 
	UCHIJAAAAAAAAAAAA	fw{1.2.2} [Fullscreen Windowed] (FullscreenWindowed-1.7.10-1.2.2c.jar) 
	UCHIJAAAAAAAAAAAA	gendustry{1.6.3.132} [GenDustry] (gendustry-1.6.3.132-mc1.7.10.jar) 
	UCHIJAAAAAAAAAAAA	InventoryTools{1.7.10-1.0.5} [Inventory Tools] (InventoryTools-1.7.10-1.0.5.jar) 
	UCHIJAAAAAAAAAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAAAAAAAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.7.10-5.1.3-unlimited.jar) 
	UCHIJAAAAAAAAAAAA	lootbags{1.8.1} [Loot Bags] (LootBags-1.7.10-1.8.1.jar) 
	UCHIJAAAAAAAAAAAA	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCHIJAAAAAAAAAAAA	Mekanism{8.1.7} [Mekanism] (Mekanism-1.7.10-8.1.7.252.jar) 
	UCHIJAAAAAAAAAAAA	MekanismGenerators{8.1.7} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.7.252.jar) 
	UCHIJAAAAAAAAAAAA	MekanismTools{8.1.7} [MekanismTools] (MekanismTools-1.7.10-8.1.7.252.jar) 
	UCHIJAAAAAAAAAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAAAAAAAAAA	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
	UCHIJAAAAAAAAAAAA	modtweaker2{0.9.5} [Mod Tweaker 2] (ModTweaker2-0.9.5.jar) 
	UCHIJAAAAAAAAAAAA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAAAAA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAAAAA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAAAAA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAAAAA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAAAAA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAAAAA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAAAAAAAAAA	neiintegration{1.1.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.1.jar) 
	UCHIJAAAAAAAAAAAA	harvestthenether{1.7.10} [Pam's Harvest the Nether] (Pam's Harvest the Nether 1.7.10a.jar) 
	UCHIJAAAAAAAAAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UCHIJAAAAAAAAAAAA	ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
	UCHIJAAAAAAAAAAAA	ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAAAAAAAAAA	ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAAAAAAAAAA	ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
	UCHIJAAAAAAAAAAAA	ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
	UCHIJAAAAAAAAAAAA	ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAAAAAAAAAA	ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
	UCHIJAAAAAAAAAAAA	ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
	UCHIJAAAAAAAAAAAA	ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAAAAAAAAAA	Roguelike{1.4.4} [Roguelike Dungeons] (roguelike-1.7.10-1.4.4.jar) 
	UCHIJAAAAAAAAAAAA	runicdungeons{1.1.6a} [Runic Dungeons] (runicdungeons-1.1.6a.jar) 
	UCHIJAAAAAAAAAAAA	Schematica{1.7.6.130} [Schematica] (Schematica-1.7.10-1.7.6.130-universal.jar) 
	UCHIJAAAAAAAAAAAA	SophisticatedWolves{3.2.0} [SophisticatedWolves] (Sophisticated Wolves 3.2.0.jar) 
	UCHIJAAAAAAAAAAAA	SpecialMobs{3.2.1} [Special Mobs] (SpecialMobs-1.7.10-3.2.1.jar) 
	UCHIJAAAAAAAAAAAA	SpiceOfLife{1.3.0} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.0.jar) 
	UCHIJAAAAAAAAAAAA	erebus{0.4.1} [Erebus] (TheErebus-0.4.1.jar) 
	UCHIJAAAAAAAAAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJAAAAAAAAAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAAAAAAAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAAAAAAAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAAAAAAAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAAAAAAAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCHIJAAAAAAAAAAAA	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
	UCHIJAAAAAAAAAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	UCHIJAAAAAAAAAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: beta rv3-beta-2 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.0.3-303
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	List of loaded APIs: 
		* AppleCoreAPI (1.1.0) from AppleCore-mc1.7.10-1.1.0.jar
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv3-beta-2.jar
		* Baubles|API (1.0.1.10) from runicdungeons-1.1.6a.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.14.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|core (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.14.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|tiles (1.1) from Railcraft_1.7.10-9.8.0.0.jar
		* BuildCraftAPI|tools (1.0) from Railcraft_1.7.10-9.8.0.0.jar
		* BuildCraftAPI|transport (4.0) from Railcraft_1.7.10-9.8.0.0.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
		* ChiselAPI (0.1.0) from Chisel2-2.5.1.44.jar
		* ChiselAPI|Carving (0.1.0) from Chisel2-2.5.1.44.jar
		* ChiselAPI|Rendering (0.1.0) from Chisel2-2.5.1.44.jar
		* CoFHAPI (1.7.10R1.0.2) from buildcraft-7.1.14.jar
		* CoFHAPI|block (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|core (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from forestry_1.7.10-4.2.3.51.jar
		* CoFHAPI|fluid (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|inventory (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|item (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|tileentity (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|transport (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|world (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|audio (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|container (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|helpers (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.2.3.51.jar
		* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.2.3.51.jar
		* ForgeRelocation|API (0.0.1.4) from ForgeRelocation-0.0.1.4-universal.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.3.132-mc1.7.10.jar
		* IC2API (1.0) from Railcraft_1.7.10-9.8.0.0.jar
		* InventoryTools|API (1.0.4) from InventoryTools-1.7.10-1.0.5.jar
		* InventoryTools|API|Dolly (1.0.4) from InventoryTools-1.7.10-1.0.5.jar
		* InventoryTools|API|Dolly|Handlers (1.0.4) from InventoryTools-1.7.10-1.0.5.jar
		* InventoryTools|API|Dolly|Handlers|Defaults (1.0.4) from InventoryTools-1.7.10-1.0.5.jar
		* InventoryTools|API|Dolly|Handlers|Defaults|Block (1.0.4) from InventoryTools-1.7.10-1.0.5.jar
		* InventoryTools|API|Dolly|Handlers|Defaults|Tile (1.0.4) from InventoryTools-1.7.10-1.0.5.jar
		* MekanismAPI|core (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
		* MekanismAPI|energy (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
		* MekanismAPI|gas (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
		* MekanismAPI|infuse (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
		* MekanismAPI|laser (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
		* MekanismAPI|reactor (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
		* MekanismAPI|recipe (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
		* MekanismAPI|transmitter (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
		* MekanismAPI|util (8.0.0) from Mekanism-1.7.10-8.1.7.252.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|carts (1.5.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|core (1.4.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|signals (1.3.4) from Railcraft_1.7.10-9.8.0.0.jar
		* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.8.0.0.jar
		* SchematicaAPI (1.1) from Schematica-1.7.10-1.7.6.130-universal.jar
		* SchematicaAPI|Events (1.1) from Schematica-1.7.10-1.7.6.130-universal.jar
		* Testerino|API (0.01) from runicdungeons-1.1.6a.jar
		* Thaumcraft|API (4.2.2.0) from runicdungeons-1.1.6a.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Yopu** [comment]
https://github.com/CovertJaguar/Railcraft/issues/753
