### ISSUE TITLE
Ayuda Error Minecraft Mods - Railcraft

### ISSUE THREAD

**Issue by JohnnyMaston** [CovertJaguar/Railcraft#782]
hola soy nuevo en esto y me ocurre el siguiente error ya llevo barios días así y no consigo cambiar nada estoy algo molesto con lo siguiente aqui el informe de error del juego:
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 9/03/16 10:09 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: cpw.mods.fml.common.registry.LanguageRegistry.loadLanguageTable(Ljava/util/Map;Ljava/lang/String;)V
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: cpw.mods.fml.common.registry.LanguageRegistry.loadLanguageTable(Ljava/util/Map;Ljava/lang/String;)V
	at need4speed402.mods.barrels.proxy.ProxyClient.init(ProxyClient.java:151)
	at need4speed402.mods.barrels.Barrels.load(Barrels.java:248)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 107318696 bytes (102 MB) / 490209280 bytes (467 MB) up to 3151495168 bytes (3005 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -Xmn200M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_D1 67 mods loaded, 67 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	appliedenergistics2-core{rv3-alpha-13} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHI	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHI	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3.jar) 
	UCHI	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
	UCHI	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHI	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHI	appliedenergistics2{rv3-alpha-13} [Applied Energistics 2] (appliedenergistics2-rv3-alpha-13.jar) 
	UCHI	ArmorStatusHUD{1.27} [ArmorStatusHUD] (ArmorStatusHUD-client-1.27.jar) 
	UCHI	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHI	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) 
	UCHI	Backpack{2.0.1} [Backpack] (Backpack-2.0.1-1.7.x.jar) 
	UCHE	barrels{3.4} [The Barrels Mod] (Barrels 3.5 - 1.7.10.jar) 
	UCHI	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHI	BiblioCraft{1.10.3} [BiblioCraft] (BiblioCraft[v1.10.3][MC1.7.10].jar) 
	UCHI	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHI	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHI	BiomesOPlenty{2.0.2} [Biomes O' Plenty] (BiomesOPlenty-1.7.2-2.0.2.932-universal.jar) 
	UCHI	ChestTransporter{2.0.3} [Chest Transporter] (ChestTransporter-2.0.3-MC1.7.10.jar) 
	UCHI	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHI	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UCHI	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHI	eplus{1.7.10-3.0.1} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.1.jar) 
	UCHI	endercore{1.7.10-0.2.0.31_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.31_beta.jar) 
	UCHI	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHI	EnderIO{1.7.10-2.3.0.422_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.422_beta.jar) 
	UCHI	ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.3-112.jar) 
	UCHI	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHI	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHI	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) 
	UCHI	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) 
	UCHI	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) 
	UCHI	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) 
	UCHI	Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) 
	UCHI	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) 
	UCHI	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) 
	UCHI	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) 
	UCHI	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) 
	UCHI	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) 
	UCHI	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCHI	IC2{2.2.807-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.807-experimental.jar) 
	UCHI	ImmibisCore{59.0.1} [Immibis Core] (immibis-core-59.0.1.jar) 
	UCHI	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHI	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHI	more{4.0} [M-Ore mod] (M-Ore 4.1.jar) 
	UCHI	meteors{2.14.2} [Falling Meteors] (meteors-1.7.10-2.14.2.jar) 
	UCHI	mythril{1.6} [Mythril mod] (mithril_mod-1.7.2-1.6.jar) 
	UCHI	movillages{1.2.1} [Mo' Villages] (MoVillages-1.3.1.jar) 
	UCHI	NuclearCraft{0.0.1.3a} [NuclearCraft] (NuclearCraft-0.0.1.3a--1.7.10.jar) 
	UCHI	plantmegapack{4.28} [Plant Mega Pack] (plantmegapack-4.28-1.7.10-1492.jar) 
	UCHI	Railcraft{9.6.0.0} [Railcraft] (Railcraft_1.7.10-9.6.0.0.jar) 
	UCHI	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
	UCHI	PowerConverters3{1.7.10-2.11} [Power Converters 3] (PowerConverters-1.7.10-2.11.jar) 
	UCHI	ProjectE{1.7.10-PE1.9.5} [ProjectE] (ProjectE-1.7.10-PE1.9.5.jar) 
	UCHI	RedLogic{59.0.2} [RedLogic] (redlogic-59.0.2.jar) 
	UCHI	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHI	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHI	TF2Teleporter{1.7.10} [TF2 Teleporter] (TF2Teleporter-1.7.10.jar) 
	UCHI	VeinMiner{0.31.4_build.unknown} [Vein Miner] (VeinMiner-1.7.10_0.31.4.unknown.jar) 
	UCHI	VeinMinerModSupport{0.31.4_build.unknown} [Mod Support] (VeinMiner-1.7.10_0.31.4.unknown.jar) 
	UCHI	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHI	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.1001' Renderer: 'AMD Radeon HD 8210'
	AE2 Version: alpha rv3-alpha-13 for Forge 10.13.4.1448
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	CoFHCore: -[1.7.10]3.1.2-325
	ThermalFoundation: -[1.7.10]1.2.3-112
	ThermalExpansion: -[1.7.10]4.1.2-240
	TConstruct Environment: Environment healthy.
	EnderIO: Found the following problem(s) with your installation:
                  * Optifine is installed. This is NOT supported.
                  * An unsupportted old RF API is installed (1.7.10R1.0.1 from Railcraft_1.7.10-9.6.0.0.jar).
                    Ender IO needs at least 1.7.10R1.0.2 and will NOT work with older versions.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) 

por favor ayuda! :(

**Comment by hea3ven** [comment]
Es un error en el mod "The Barrels Mod", proba de actualizarlo. Y si no funciona pedí ayuda en el post de ese mod.

**Comment by JohnnyMaston** [comment]
Perfecto muchas gracias y si tenia actualizado el "The Barrels Mod" así que preferí quitarlo enserio eso soluciono el problema muchas gracias te la debo :) te has ganado un suscriptor fu
