### ISSUE TITLE
World anchor causes NPE in Forge

### ISSUE THREAD

**Issue by cobra** [CovertJaguar/Railcraft#783]
I have one Admin Anchor placed in the overworld. When I saved and quit to title while in the nether and loaded this world again, I got this crash. Loading the world after starting MC again does work without any further measures. Saving, quitting and reloading after this restart makes MC crash again each time (still in the nether). Singleplayer, integrated Server.
Might be related to #753.
Version: 9.9.0.0; Forge 1.7.10-10.13.4.1614

````
[Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.world.WorldEvent$Load@215f6b44:
java.lang.NullPointerException
	at net.minecraftforge.common.ForgeChunkManager.releaseTicket(ForgeChunkManager.java:695) ~[ForgeChunkManager.class:?]
	at mods.railcraft.common.blocks.machine.alpha.TileAnchorWorld.setTicket(TileAnchorWorld.java:373) ~[TileAnchorWorld.class:?]
	at mods.railcraft.common.blocks.machine.alpha.TileAnchorWorld.forceChunkLoading(TileAnchorWorld.java:386) ~[TileAnchorWorld.class:?]
	at mods.railcraft.common.util.misc.ChunkManager.ticketsLoaded(ChunkManager.java:174) ~[ChunkManager.class:?]
	at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:523) ~[ForgeChunkManager.class:?]
	at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:64) ~[ForgeInternalHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_4_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73) [bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
````

**Comment by cobra** [comment]
Built and tested b8d388c8988301282c3d8ea2dadcb24697ff2eac myself, doesn't crash any more. Yay!
