### ISSUE TITLE
Signal Label may crashes the game with NullPointerException

### ISSUE THREAD

**Issue by xingrz** [CovertJaguar/Railcraft#793]
The crash seems to be brought since 9.9.0.0, and still there at 9.10.0.0

The game will suddenly crashed without any noticeable presage. After that, the saved game couldn't be played any more (crash immediately after loaded).

This has happened many times (I backed up the save)

```
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at mods.railcraft.client.render.RenderTESRSignals.func_147500_a(RenderTESRSignals.java:71)
	at mods.railcraft.client.render.RenderSignal.func_147500_a(RenderSignal.java:208)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
	at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:772)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1596)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1334)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:154)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mods.railcraft.client.render.RenderTESRSignals.func_147500_a(RenderTESRSignals.java:71)
	at mods.railcraft.client.render.RenderSignal.func_147500_a(RenderSignal.java:208)

-- Block Entity Details --
Details:
	Name: RCTileStructureBlockSignal // mods.railcraft.common.blocks.signals.TileSignalBlockSignal
	Block type: ID #435 (tile.railcraft.signal // mods.railcraft.common.blocks.signals.BlockSignalRailcraft)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (369,53,265), Chunk: (at 1,3,9 in 23,16; contains blocks 368,0,256 to 383,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #435 (tile.railcraft.signal // mods.railcraft.common.blocks.signals.BlockSignalRailcraft)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
	at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:772)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1596)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['XiNGRZ'/280, l='MpServer', x=373.46, y=54.82, z=267.47]]
	Chunk stats: MultiplayerChunkCache: 515, 524
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options:
	Level spawn location: World: (132,64,248), Chunk: (at 4,4,8 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 7953365 game time, 1028729 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 59 total; [EntityCow['Cow'/389, l='MpServer', x=447.63, y=68.00, z=189.22], EntityCreeper['Creeper'/262, l='MpServer', x=399.03, y=63.00, z=300.38], EntityCow['Cow'/390, l='MpServer', x=445.31, y=69.00, z=195.38], EntityCow['Cow'/391, l='MpServer', x=436.72, y=75.00, z=205.47], EntityLocomotiveElectric['Electric Locomotive'/8, l='MpServer', x=383.50, y=52.50, z=268.50], EntityCreeper['Creeper'/264, l='MpServer', x=341.90, y=64.00, z=286.46], EntityZombie['Zombie'/392, l='MpServer', x=435.50, y=24.00, z=328.50], EntityCartBasic['entity.MinecartRideable.name'/9, l='MpServer', x=381.78, y=52.50, z=268.50], EntityCartAnchorAdmin['Admin Anchor Cart'/10, l='MpServer', x=380.28, y=52.50, z=268.50], EntityCartBasic['entity.MinecartRideable.name'/11, l='MpServer', x=378.78, y=52.50, z=268.50], EntityBat['Bat'/267, l='MpServer', x=358.83, y=31.00, z=220.05], EntityCartBasic['entity.MinecartRideable.name'/12, l='MpServer', x=377.41, y=52.50, z=268.50], EntityCow['Cow'/268, l='MpServer', x=364.69, y=63.00, z=239.31], EntityCartAnchorAdmin['Admin Anchor Cart'/13, l='MpServer', x=376.09, y=52.50, z=268.50], EntityCartBasic['entity.MinecartRideable.name'/14, l='MpServer', x=374.78, y=52.50, z=268.50], EntityCreeper['Creeper'/398, l='MpServer', x=452.50, y=69.00, z=189.50], EntityLocomotiveElectric['Electric Locomotive'/15, l='MpServer', x=373.50, y=52.50, z=268.50], EntitySpider['Spider'/16, l='MpServer', x=374.47, y=73.00, z=254.00], EntitySkeleton['Skeleton'/17, l='MpServer', x=366.19, y=73.00, z=260.63], EntityZombie['Zombie'/273, l='MpServer', x=414.50, y=69.00, z=248.50], EntitySpider['Spider'/18, l='MpServer', x=365.01, y=73.00, z=261.59], EntityZombie['Zombie'/35, l='MpServer', x=294.50, y=39.00, z=264.50], EntitySpider['Spider'/47, l='MpServer', x=361.70, y=73.00, z=266.05], EntitySkeleton['Skeleton'/48, l='MpServer', x=369.48, y=73.00, z=262.35], EntityZombie['Zombie'/49, l='MpServer', x=308.45, y=66.00, z=265.81], EntitySquid['Squid'/316, l='MpServer', x=352.75, y=61.32, z=312.72], EntityCreeper['Creeper'/326, l='MpServer', x=365.50, y=31.00, z=205.50], EntityChicken['Chicken'/327, l='MpServer', x=363.28, y=68.00, z=218.69], EntityCreeper['Creeper'/328, l='MpServer', x=365.80, y=67.00, z=209.69], EntitySquid['Squid'/329, l='MpServer', x=358.68, y=60.35, z=317.11], EntitySquid['Squid'/330, l='MpServer', x=354.48, y=60.00, z=320.33], EntitySquid['Squid'/331, l='MpServer', x=357.68, y=60.36, z=317.41], EntityZombie['Zombie'/345, l='MpServer', x=374.53, y=31.35, z=206.68], EntityChicken['Chicken'/346, l='MpServer', x=374.53, y=31.00, z=206.78], EntityCow['Cow'/347, l='MpServer', x=381.88, y=68.00, z=199.06], EntityCreeper['Creeper'/348, l='MpServer', x=375.50, y=37.00, z=208.50], EntitySkeleton['Skeleton'/349, l='MpServer', x=370.50, y=68.00, z=218.50], EntityWitch['Witch'/226, l='MpServer', x=300.50, y=18.00, z=246.50], EntityWitch['Witch'/227, l='MpServer', x=298.50, y=18.00, z=249.50], EntityWitch['Witch'/228, l='MpServer', x=303.88, y=18.00, z=255.31], EntityWitch['Witch'/229, l='MpServer', x=296.50, y=18.00, z=248.50], EntityBat['Bat'/232, l='MpServer', x=295.45, y=19.00, z=244.20], EntityCreeper['Creeper'/233, l='MpServer', x=294.50, y=39.00, z=273.50], EntityCreeper['Creeper'/235, l='MpServer', x=302.56, y=64.00, z=288.44], EntityCreeper['Creeper'/365, l='MpServer', x=414.50, y=68.00, z=189.50], EntityCow['Cow'/366, l='MpServer', x=412.50, y=62.48, z=342.05], EntityZombie['Zombie'/239, l='MpServer', x=306.50, y=68.00, z=222.50], EntityCreeper['Creeper'/240, l='MpServer', x=308.18, y=66.00, z=284.18], EntityCreeper['Creeper'/241, l='MpServer', x=311.50, y=66.00, z=286.50], EntityClientPlayerMP['XiNGRZ'/280, l='MpServer', x=373.46, y=54.82, z=267.47], EntitySquid['Squid'/374, l='MpServer', x=414.88, y=61.00, z=333.30], EntityZombie['Zombie'/247, l='MpServer', x=327.72, y=43.00, z=219.22], EntitySquid['Squid'/375, l='MpServer', x=430.60, y=61.27, z=320.22], EntityBat['Bat'/248, l='MpServer', x=332.77, y=50.83, z=219.84], EntitySquid['Squid'/376, l='MpServer', x=415.64, y=61.35, z=318.13], EntitySpider['Spider'/249, l='MpServer', x=329.28, y=71.00, z=229.16], EntitySquid['Squid'/377, l='MpServer', x=425.97, y=62.42, z=327.37], EntityCow['Cow'/250, l='MpServer', x=335.78, y=66.00, z=283.31], EntityZombie['Zombie'/251, l='MpServer', x=331.50, y=64.00, z=297.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:154)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.11.4
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 661445008 bytes (630 MB) / 2847494144 bytes (2715 MB) up to 4080271360 bytes (3891 MB)
	JVM Flags: 6 total; -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn2048m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D3 57 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar)
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar)
	UCHIJAAAA	OpenComputers|Core{1.5.22.46} [OpenComputers (Core)] (minecraft.jar)
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar)
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar)
	UCHIJAAAA	asielib{0.4.5} [asielib] (AsieLib-1.7.10-0.4.5.jar)
	UCHIJAAAA	BuildCraft|Core{7.1.16} [BuildCraft] (buildcraft-7.1.16.jar)
	UCHIJAAAA	BuildCraft|Builders{7.1.16} [BC Builders] (buildcraft-7.1.16.jar)
	UCHIJAAAA	BuildCraft|Transport{7.1.16} [BC Transport] (buildcraft-7.1.16.jar)
	UCHIJAAAA	BuildCraft|Energy{7.1.16} [BC Energy] (buildcraft-7.1.16.jar)
	UCHIJAAAA	BuildCraft|Silicon{7.1.16} [BC Silicon] (buildcraft-7.1.16.jar)
	UCHIJAAAA	BuildCraft|Robotics{7.1.16} [BC Robotics] (buildcraft-7.1.16.jar)
	UCHIJAAAA	BuildCraft|Factory{7.1.16} [BC Factory] (buildcraft-7.1.16.jar)
	UCHIJAAAA	BuildCraft|Compat{7.1.4} [BuildCraft Compat] (buildcraft-compat-7.1.4.jar)
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar)
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.2B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UCHIJAAAA	IC2{2.2.817-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.817-experimental.jar)
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar)
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar)
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar)
	UCHIJAAAA	OpenComputers{1.5.22.46} [OpenComputers] (OpenComputers-MC1.7.10-1.5.22.46-universal.jar)
	UCHIJAAAA	Railcraft{9.10.0.0} [Railcraft] (Railcraft_1.7.10-9.10.0.0.jar)
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar)
	UCHIJAAAA	computronics{1.6.0} [Computronics] (Computronics-1.7.10-1.6.0.jar)
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar)
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar)
	UCHIJAAAA	IC2NuclearControl{2.3.4a} [Nuclear Control 2] (IC2NuclearControl-2.3.4a.jar)
	UCHIJAAAA	ImmibisCore{59.1.4} [Immibis Core] (immibis-core-59.1.4.jar)
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar)
	UCHIJAAAA	journeymap{5.1.4} [JourneyMap] (journeymap-1.7.10-5.1.4-unlimited.jar)
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar)
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar)
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.2B1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.2B1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.2B1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.2B1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.2B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar)
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar)
	UCHIJAAAA	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar)
	UCHIJAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar)
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
	UD	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.2B1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.2B1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.2B1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.2B1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.2B1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.2B1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.2B1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.2B1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UD	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.2B1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UD	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.2B1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UD	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.2B1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.2B1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar)
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.10.5.2 310.42.25f01' Renderer: 'NVIDIA GeForce GT 650M OpenGL Engine'
	CoFHCore: -[1.7.10]3.1.2-325
	MineFactoryReloaded: -[1.7.10]2.8.2B1-177
	Launched Version: Hello Minecraft! Launcher 2.3.5.7
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GT 650M OpenGL Engine GL version 2.1 NVIDIA-10.10.5.2 310.42.25f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)
	OptiFine Version: OptiFine_1.7.10_HD_U_D3
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 16
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 2.1 NVIDIA-10.10.5.2 310.42.25f01
	OpenGlRenderer: NVIDIA GeForce GT 650M OpenGL Engine
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by xingrz** [comment]
The crash haven't occurred for a long time after I disabled these mods:

```
InventoryTweaks-1.59-dev-152.jar
journeymap-1.7.10-5.1.4-unlimited.jar
OptiFine_1.7.10_HD_U_D3.jar
ShadersModCore-v2.3.31-mc1.7.10-f.jar
Waila-1.5.10_1.7.10.jar
Wawla-1.3.3-1.7.10.jar
worldedit-forge-mc1.7.10-6.0-beta-01.jar
```

I'm trying to investigate which mod cause the crash.

**Comment by Landrash** [comment]
Try it without shaders and optifine. Since it's seems to be a render related crash that would be my guess.

**Comment by xingrz** [comment]
@Landrash Yes, I leave those 2 mod disabled and it seems work properly for a while. I'm now investigating what action exactly cause the crash.

**Comment by xingrz** [comment]
I disabled each of those possible mods. The problem seems to be brought by `InventoryTweaks-1.59-dev-152`

**Comment by xingrz** [comment]
@Landrash seems not related to shaders or optifine, but to malisisdoors

I've found a motion to reproduce the crash.

**Comment by xingrz** [comment]
If found the crash line is [here](https://github.com/CovertJaguar/Railcraft/blob/9.10.0.0-master/src/main/java/mods/railcraft/client/render/RenderTESRSignals.java#L71), which I think the `mop` is `null`.

**Comment by xingrz** [comment]
Okay, here's the way to crash the game.

1. Says we have a platform with more than 8 screen doors (by malisisdoors 1.13.2)
2. A Signal Box with Signal Label at the head of the platform
3. Fly close to the platform, them move horizontally with `A` (see the picture below)
4. It crashes

the crashing save is here: [Crash.zip](https://github.com/CovertJaguar/Railcraft/files/190501/Crash.zip)

<img width="1090" alt="2016-03-26 21 56 17" src="https://cloud.githubusercontent.com/assets/288288/14060373/ae734b92-f39d-11e5-9b75-926d7bf6859a.png">
